from pathlib import Path

p = Path('torn-trade-analyzer.user.js')
s = p.read_text(encoding='utf-8')

def once(old, new, label):
    global s
    n = s.count(old)
    if n != 1:
        raise SystemExit(f'{label}: expected 1 match, found {n}')
    s = s.replace(old, new, 1)

once('// @version      0.2.16', '// @version      0.2.17', 'metadata version')
once("const VERSION = '0.2.16';", "const VERSION = '0.2.17';", 'runtime version')

marker = '''      @media(max-width:520px){.tta-content{padding-left:10px;padding-right:10px}.tta-period{align-items:stretch;flex-direction:column}.tta-syncactions{width:100%;display:grid;grid-template-columns:1fr 1fr}.tta-syncactions .tta-btn{width:100%}.tta-position-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.tta-position-grid .tta-bento:last-child{grid-column:1/-1}.tta-listtools{grid-template-columns:1fr}.tta-consolidated{font-size:27px!important}.tta-help-grid{grid-template-columns:1fr}.tta-help-card.wide{grid-column:auto}.tta-portal-head{align-items:flex-start;flex-direction:column}.tta-nw-delta{grid-template-columns:1fr}.tta-nw-delta span{text-align:left;max-width:none}.tta-nw-change{grid-template-columns:32px minmax(0,1fr)}.tta-nw-change-value{grid-column:2;text-align:left}}\n'''

compact = r'''      /* v0.2.17 compact UI consistency sweep */
      #tta-fab{width:42px;height:42px;min-width:42px;min-height:42px;border-radius:14px;box-shadow:0 10px 24px #07151e5c,0 0 0 1px #79dfb312,inset 0 1px #ffffff27,inset 0 -8px 16px #0d1b2428}
      #tta-fab:before{left:6px;right:6px;top:4px}#tta-fab:after{width:21px;height:21px;right:-7px;bottom:-7px}
      #tta-fab .tta-fabicon,#tta-fab .tta-fabicon svg{width:25px;height:25px}#tta-fab .tta-fabspinner{width:18px;height:18px;flex-basis:18px}
      #tta-fab:hover{box-shadow:0 12px 27px #07151e68,0 0 0 1px #79dfb320,0 0 16px #91cdf719,inset 0 1px #ffffff32}
      #tta-fab.dragging{box-shadow:0 13px 30px #07151e70,0 0 18px #79dfb320,inset 0 1px #ffffff34}
      #tta-fab.syncing{box-shadow:0 11px 27px #07151e68,0 0 18px #79dfb320,inset 0 1px #ffffff2b}

      .tta-header{min-height:56px;padding:8px 10px;gap:7px}.tta-brand{gap:7px}.tta-mark{width:34px;height:34px;flex-basis:34px;border-radius:10px;font-size:17px}.tta-title{font-size:15px}.tta-sub{font-size:10px;margin-top:1px}.tta-iconbtn,.tta-back{width:36px;height:36px;min-width:36px;min-height:36px;flex-basis:36px;border-radius:10px;font-size:17px}.tta-back{font-size:23px}
      .tta-content{padding:11px 10px 28px!important}.tta-search{top:56px;padding-bottom:8px}.tta-search input{min-height:40px;padding:9px 11px;font-size:12px}
      .tta-period{gap:8px;padding:9px 10px;margin-bottom:9px;border-radius:14px}.tta-period strong{font-size:13px}.tta-periodhint{line-height:1.35}.tta-syncactions{gap:5px}.tta-syncactions .tta-btn{min-height:32px;padding:6px 8px;font-size:9.5px}
      .tta-chips{gap:6px;padding-bottom:3px}.tta-chip{min-height:31px;padding:6px 9px;font-size:10px}
      .tta-summary{gap:6px;margin:9px 0}.tta-stat{padding:9px;border-radius:12px}.tta-stat label{font-size:8px;letter-spacing:.55px}.tta-stat b{font-size:clamp(12px,3.7vw,15px);margin-top:4px}.tta-stat.main b{font-size:clamp(17px,5vw,20px)}
      .tta-chartcard{padding:11px 9px 9px;margin-bottom:11px;border-radius:15px!important}.tta-charthead{gap:7px;margin-bottom:7px}.tta-charthead h3{font-size:12px}.tta-charthead small{font-size:9px}.tta-chartinteractive{padding-top:45px}.tta-svg{height:150px}.tta-charttooltip{max-width:170px;padding:7px 8px}
      .tta-empty{min-height:92px;gap:7px;padding:14px;font-size:11px}.tta-sectionhead{flex-wrap:wrap;align-items:flex-start;gap:7px;margin:7px 1px 8px}.tta-sectionhead>div{min-width:0;flex:1 1 175px}.tta-sectionhead h3{font-size:13px}.tta-sectionhint{max-width:46%;text-align:right;line-height:1.35;white-space:normal}.tta-btn{min-height:35px;padding:7px 10px;font-size:10.5px;border-radius:11px}

      .tta-item{margin-bottom:8px;border-radius:14px!important}.tta-itemtop{grid-template-columns:42px minmax(0,1fr) auto;gap:8px;min-height:62px;padding:8px 9px}.tta-thumbwrap{width:42px;height:42px;border-radius:10px}.tta-thumb{width:35px;height:35px;max-width:35px;max-height:35px}.tta-itemname{font-size:12px}.tta-source{font-size:9px;margin-top:3px;line-height:1.3}.tta-itemfacts{gap:4px;margin-top:5px}.tta-factpill{min-height:19px;padding:3px 5px;font-size:8px}.tta-factpill.market{font-size:8.5px}.tta-profitbox{min-width:64px;max-width:90px}.tta-profit{font-size:11.5px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.tta-chevron{font-size:9px;margin-top:3px}.tta-cardactions{gap:4px;margin-bottom:3px}.tta-pin,.tta-hideitem{width:28px;height:28px;min-width:28px;min-height:28px;border-radius:8px}.tta-pin{font-size:13px}.tta-hideitem{font-size:12px}.tta-metric{padding:7px 5px}.tta-metric small{font-size:8px}.tta-metric b{font-size:11px}.tta-accordion{padding:10px}.tta-minirow{gap:5px;margin-bottom:8px}.tta-ministat{padding:7px 5px}.tta-ministat small{font-size:8px}.tta-ministat b{font-size:10.5px}
      .tta-listtools{gap:6px;margin:6px 0 3px}.tta-history-search{min-height:39px;padding:8px 10px;font-size:11px}.tta-sortbtn{min-width:104px}.tta-listmeta{font-size:9px;margin-bottom:8px}.tta-result{grid-template-columns:42px minmax(0,1fr) auto;gap:8px;padding:8px 9px;min-height:60px;margin-bottom:7px}.tta-result small{font-size:9px}

      .tta-banner{padding:9px 10px;margin-bottom:9px;border-radius:12px!important;line-height:1.45}.tta-keycard{padding:10px;margin:10px 0}.tta-keyhead{margin-bottom:7px}.tta-keyinputrow{gap:6px}.tta-keyinputrow input{min-height:39px;padding:8px 9px}.tta-keynote{margin-top:7px;line-height:1.45}.tta-settings label{margin:11px 0 4px}.tta-settings-actions{gap:6px;margin-top:9px}.tta-tos{padding:9px 10px;line-height:1.5}.tta-hiddenlist{gap:6px}.tta-hiddenrow{padding:7px 8px}.tta-hiddenrow .tta-btn{min-height:30px;padding:5px 8px}

      .tta-ledgerintro{gap:7px;margin-bottom:8px;flex-wrap:wrap}.tta-ledgerintro>div{min-width:0;flex:1 1 190px}.tta-ledgerfilters{gap:6px;margin:8px 0}.tta-ledgerfilters input,.tta-ledgerfilters select{min-height:38px;padding:7px 9px;font-size:10px}.tta-ledgersummary{gap:5px;margin:8px 0}.tta-ledgertable{min-width:860px}.tta-ledgertable th button{padding:8px 7px;font-size:8.5px}.tta-ledgertable td{padding:7px;font-size:9.5px}.tta-ledgeritem{min-width:122px}.tta-ledgermethod{min-width:112px}.tta-ledgerstatus{min-width:96px}.tta-ledgermeta{gap:7px;margin:6px 1px;font-size:9px}.tta-ledgermore{margin-top:9px}

      .tta-bento-grid{gap:8px;margin:8px 0}.tta-bento{padding:11px;border-radius:15px}.tta-bento b{font-size:clamp(12px,3.8vw,15px);margin-top:4px}.tta-bento p{margin-top:5px;line-height:1.4}.tta-bento-hero{padding:14px}.tta-consolidated{font-size:26px!important;margin-top:5px!important}.tta-equation{margin-top:6px;gap:6px}.tta-sectionintro{margin:12px 2px 6px}.tta-sectionintro h3,.tta-sectionhead h3{font-size:13px}
      .tta-feature-portal{margin:11px 0 14px;padding:10px;border-radius:17px}.tta-portal-head{gap:7px;margin:0 1px 8px}.tta-portal-head h3{font-size:14px}.tta-feature-portal .tta-fin-nav{gap:7px!important}.tta-feature-portal .tta-toolcard{flex-basis:clamp(184px,66vw,226px);min-height:88px;padding:10px 11px;grid-template-columns:36px minmax(0,1fr);gap:9px;border-radius:14px}.tta-feature-portal .tta-toolcard:after{right:9px;top:6px;font-size:20px}.tta-tool-icon{width:36px;height:36px;border-radius:11px;font-size:18px}.tta-toolcopy strong{font-size:12px!important}.tta-toolcopy small{font-size:8.5px!important;line-height:1.35;padding-right:9px}.tta-toolcopy em{margin-top:5px;font-size:8px}.tta-position-grid{gap:7px;margin-bottom:9px}.tta-position-grid .tta-bento{padding:9px}.tta-position-grid .tta-bento b{font-size:clamp(11px,3.5vw,13px)}
      .tta-glass-section{padding:10px;margin:9px 0}.tta-fin-section{padding:10px;margin:9px 0}.tta-fin-section h3{font-size:12px;margin-bottom:7px}.tta-cashhero{gap:6px;margin:8px 0 10px}.tta-cashcard{padding:9px}.tta-cashcard small{font-size:8px}.tta-cashcard b{font-size:clamp(12px,3.8vw,15px);margin-top:4px}.tta-fin-grid{gap:5px}.tta-fin-row{gap:7px;padding:6px 0;font-size:9.5px;align-items:flex-start}.tta-fin-row span{min-width:0;overflow-wrap:anywhere}.tta-fin-row b{flex:0 0 auto;max-width:55%;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.tta-breakdown{gap:4px}.tta-breakrow{gap:6px;padding:6px 7px;font-size:9px}.tta-networth-total{font-size:clamp(20px,7vw,25px)!important}.tta-snapshot-note{margin-top:5px;line-height:1.4}
      .tta-flowtable{min-width:520px;font-size:9.5px}.tta-flowtable th{padding:7px 6px;font-size:8.5px}.tta-flowtable td{padding:7px 6px}.tta-flowtitle{display:block;line-height:1.3}.tta-flowmeta{font-size:8px;line-height:1.35}.tta-flowbadge{font-size:7.5px;padding:3px 5px}

      .tta-help-intro{padding:11px;margin-bottom:9px;border-radius:15px}.tta-help-intro h2{font-size:15px;margin-bottom:4px}.tta-help-intro p{font-size:9.5px;line-height:1.45}.tta-help-grid{gap:7px}.tta-help-card{padding:10px;border-radius:14px}.tta-help-card .icon{width:30px;height:30px;margin-bottom:6px;border-radius:9px;font-size:15px}.tta-help-card h3{font-size:11.5px;margin-bottom:4px}.tta-help-card p{font-size:8.7px;line-height:1.45}
      .tta-nw-daily{margin-top:9px}.tta-nw-delta{gap:8px;padding:9px 10px;margin:6px 0 8px}.tta-nw-delta b{font-size:clamp(16px,5vw,19px)}.tta-nw-delta span{max-width:190px}.tta-nw-change-list{gap:5px}.tta-nw-change{grid-template-columns:30px minmax(0,1fr) auto;gap:7px;padding:7px 8px;border-radius:11px}.tta-nw-change-icon{width:30px;height:30px;border-radius:9px;font-size:14px}.tta-nw-change-copy strong{font-size:10px;white-space:normal;line-height:1.3}.tta-nw-change-copy small{font-size:8px;line-height:1.3}.tta-nw-change-value{font-size:clamp(8.5px,2.6vw,9.5px);max-width:120px;overflow:hidden;text-overflow:ellipsis}.tta-nw-disclaimer{margin-top:6px;line-height:1.4}

      .tta-loading{padding:14px}.tta-loadingcard{padding:14px;border-radius:16px}.tta-loadicon{width:44px;height:44px;margin-bottom:9px;border-radius:13px}.tta-loadingdetail{min-height:28px;margin-top:5px;font-size:10px}.tta-loadingbar{margin:10px 0}.tta-loadinghint{margin-top:7px}.tta-toast{max-width:min(90vw,420px);white-space:normal;overflow-wrap:anywhere;padding:8px 11px;font-size:10px}

      @media(max-width:520px){
        .tta-header{padding-left:8px;padding-right:8px;gap:5px}.tta-brand{gap:5px}.tta-mark{width:30px;height:30px;flex-basis:30px;font-size:15px}.tta-title{font-size:14px}.tta-sub{font-size:9px}.tta-iconbtn,.tta-back{width:34px;height:34px;min-width:34px;min-height:34px;flex-basis:34px}.tta-content{padding-left:8px!important;padding-right:8px!important}.tta-period{padding:8px 9px}.tta-bento-grid{gap:7px}.tta-bento{padding:10px}.tta-bento-hero{padding:12px}.tta-consolidated{font-size:24px!important}.tta-feature-portal{padding:9px}.tta-feature-portal .tta-toolcard{flex-basis:min(76vw,215px)}.tta-sectionhint{max-width:none;text-align:left}.tta-keyinputrow{grid-template-columns:1fr}.tta-keyinputrow .tta-btn{width:100%}.tta-nw-change{grid-template-columns:28px minmax(0,1fr)}.tta-nw-change-icon{width:28px;height:28px}.tta-nw-change-value{grid-column:2;max-width:none;text-align:left}.tta-fin-row b{max-width:52%}.tta-flowtable{min-width:500px}
      }
      @media(max-width:380px){
        .tta-header{gap:4px}.tta-mark{display:none}.tta-iconbtn,.tta-back{width:32px;height:32px;min-width:32px;min-height:32px;flex-basis:32px}.tta-sub{max-width:145px}.tta-summary{grid-template-columns:1.35fr .9fr .9fr}.tta-stat{padding:8px 5px}.tta-itemtop{grid-template-columns:40px minmax(0,1fr) auto;gap:6px;padding:7px}.tta-thumbwrap{width:40px;height:40px}.tta-profitbox{min-width:58px;max-width:76px}.tta-cardactions{gap:3px}.tta-pin,.tta-hideitem{width:26px;height:26px;min-width:26px;min-height:26px}.tta-factpill:not(.market){display:none}.tta-feature-portal .tta-toolcard{flex-basis:78vw}.tta-flowtable{min-width:480px}
      }
'''

once(marker, marker + compact, 'compact UI CSS insertion')
p.write_text(s, encoding='utf-8')
