from pathlib import Path

p=Path('torn-trade-analyzer.user.js')
s=p.read_text(encoding='ascii')

def rep(old,new,label):
    global s
    if old not in s:
        raise SystemExit(f'missing anchor: {label}')
    s=s.replace(old,new,1)

rep('// @version      0.2.42','// @version      0.2.43','version header')
rep("const VERSION = '0.2.42';","const VERSION = '0.2.43';",'version const')

old_tx="""    for(const t of state.transactions||[]){const ts=Number(t?.timestamp)||0;if(ts<from||ts>to||Number(t?.logId)===4103)continue;const item=catalogItem(t.itemId),q=Math.max(0,Number(t.qty)||0);if(!(q>0))continue;if(t.side==='buy'){const cost=Math.max(0,Number(t.total)||0),market=q*Math.max(0,Number(item.marketPrice)||0),free=!!t.free;rows.push({timestamp:ts,kind:'item-in',icon:'\\uFF0B',title:`Acquired ${qty(q)} \\u00D7 ${item.name}`,meta:`${t.source||'Item acquisition'} \\u00B7 ${free?'Free / $0 cost':`Cost ${money(cost)}`}${market?` \\u00B7 Est. current value ${money(market)}`:''}`,value:market||cost,valueClass:'pos',prefix:'+'});}else if(t.side==='sell'){const proceeds=Math.max(0,Number(t.netTotal??t.total)||0),evt=(fifoAnalytics(t.itemId).events||[]).find(e=>String(e.id)===String(t.id)),profit=Number(evt?.realizedProfit),known=Number.isFinite(profit);rows.push({timestamp:ts,kind:'item-sale',icon:'\\u2197',title:`Sold ${qty(q)} \\u00D7 ${item.name}`,meta:`${t.source||'Item sale'} \\u00B7 Net proceeds ${money(proceeds)}${known?` \\u00B7 FIFO ${profit>=0?'profit':'loss'} ${money(Math.abs(profit))}`:' \\u00B7 FIFO profit/loss unavailable'}`,value:known?Math.abs(profit):0,valueClass:known?(profit>=0?'pos':'neg'):'',prefix:known?(profit>=0?'+':'-'):''});}}"""
new_tx="""    for(const t of state.transactions||[]){const ts=Number(t?.timestamp)||0;if(ts<from||ts>to||Number(t?.logId)===4103)continue;const item=catalogItem(t.itemId),q=Math.max(0,Number(t.qty)||0);if(!(q>0))continue;if(t.side==='buy'){const cost=Math.max(0,Number(t.total)||0),market=q*Math.max(0,Number(item.marketPrice)||0),free=!!t.free,marketKnown=market>0,impact=free?(marketKnown?market:0):(marketKnown?market-cost:0),impactKnown=free?marketKnown:marketKnown,costLabel=t.source==='Player Trade'?'Allocated trade cash':'Cash paid',impactMeta=impactKnown?` \\u00B7 Est. net-worth impact ${impact>=0?'+':''}${money(impact)}`:' \\u00B7 Net-worth impact unavailable (no item market value)';rows.push({timestamp:ts,kind:'item-in',icon:'\\uFF0B',title:`${free?'Acquired':'Bought'} ${qty(q)} \\u00D7 ${item.name}`,meta:`${t.source||'Item acquisition'} \\u00B7 ${free?'Free / $0 cost':`${costLabel} -${money(cost)}`}${marketKnown?` \\u00B7 Item value +${money(market)}`:''}${impactMeta}`,value:impactKnown?Math.abs(impact):0,valueClass:impactKnown?(impact>=0?'pos':'neg'):'',prefix:impactKnown?(impact>=0?'+':'-'):'',impact:impactKnown?impact:null,impactKnown});}else if(t.side==='sell'){const proceeds=Math.max(0,Number(t.netTotal??t.total)||0),market=q*Math.max(0,Number(item.marketPrice)||0),marketKnown=market>0,impact=marketKnown?proceeds-market:0,evt=(fifoAnalytics(t.itemId).events||[]).find(e=>String(e.id)===String(t.id)),profit=Number(evt?.realizedProfit),profitKnown=Number.isFinite(profit),impactMeta=marketKnown?` \\u00B7 Est. net-worth impact ${impact>=0?'+':''}${money(impact)}`:' \\u00B7 Net-worth impact unavailable (no item market value)';rows.push({timestamp:ts,kind:'item-sale',icon:'\\u2197',title:`Sold ${qty(q)} \\u00D7 ${item.name}`,meta:`${t.source||'Item sale'} \\u00B7 Cash received +${money(proceeds)}${marketKnown?` \\u00B7 Item value removed -${money(market)}`:''}${impactMeta}${profitKnown?` \\u00B7 FIFO trade ${profit>=0?'profit':'loss'} ${money(Math.abs(profit))}`:' \\u00B7 FIFO profit/loss unavailable'}`,value:marketKnown?Math.abs(impact):0,valueClass:marketKnown?(impact>=0?'pos':'neg'):'',prefix:marketKnown?(impact>=0?'+':'-'):'',impact:marketKnown?impact:null,impactKnown:marketKnown});}}"""
rep(old_tx,new_tx,'item transaction net worth modeling')

old_transfer="""    for(const t of state.playerTransfers||[]){const ts=Number(t?.timestamp)||0;if(ts<from||ts>to||t?.type!=='item')continue;const item=catalogItem(t.itemId),q=Math.max(0,Number(t.qty)||0),market=q*Math.max(0,Number(item.marketPrice)||0),incoming=t.direction==='in',who=t.counterpartyName||((Number(t.counterpartyId)||0)>0?`#${t.counterpartyId}`:'another player');rows.push({timestamp:ts,kind:incoming?'player-item-in':'player-item-out',icon:incoming?'\\u21E3':'\\u21E1',title:`${incoming?'Received':'Sent'} ${qty(q)} \\u00D7 ${item.name}`,meta:`Player transfer ${incoming?'from':'to'} ${who}${t.message?` \\u00B7 ${t.message}`:''}${market?` \\u00B7 Est. value ${money(market)}`:''}`,value:market,valueClass:incoming?'pos':'neg',prefix:incoming?'+':'-'});}"""
new_transfer="""    for(const t of state.playerTransfers||[]){const ts=Number(t?.timestamp)||0;if(ts<from||ts>to||t?.type!=='item')continue;const item=catalogItem(t.itemId),q=Math.max(0,Number(t.qty)||0),market=q*Math.max(0,Number(item.marketPrice)||0),incoming=t.direction==='in',who=t.counterpartyName||((Number(t.counterpartyId)||0)>0?`#${t.counterpartyId}`:'another player'),impactKnown=market>0,impact=impactKnown?(incoming?market:-market):0;rows.push({timestamp:ts,kind:incoming?'player-item-in':'player-item-out',icon:incoming?'\\u21E3':'\\u21E1',title:`${incoming?'Received':'Sent'} ${qty(q)} \\u00D7 ${item.name}`,meta:`Player transfer ${incoming?'from':'to'} ${who}${t.message?` \\u00B7 ${t.message}`:''}${market?` \\u00B7 Est. value ${money(market)}`:' \\u00B7 Net-worth impact unavailable (no item market value)'}`,value:impactKnown?market:0,valueClass:impactKnown?(incoming?'pos':'neg'):'',prefix:impactKnown?(incoming?'+':'-'):'',impact:impactKnown?impact:null,impactKnown});}"""
rep(old_transfer,new_transfer,'player transfer impact')

old_consume="""    for(const g of consumptionGroups.values()){rows.push({timestamp:g.timestamp,kind:'item-consumed',icon:'\\u2212',title:`Used ${qty(g.qty)} \\u00D7 ${g.itemName}`,meta:`${g.title}${g.count>1?` \\u00B7 ${qty(g.count)} use logs combined`:''}${g.market?` \\u00B7 Est. value removed ${money(g.market)}`:''}${g.basis?` \\u00B7 FIFO cost basis removed ${money(g.basis)}`:''}`,value:g.market||g.basis,valueClass:'neg',prefix:'-'});}"""
new_consume="""    for(const g of consumptionGroups.values()){const impactValue=g.market||g.basis,impact=impactValue>0?-impactValue:0,impactKnown=impactValue>0;rows.push({timestamp:g.timestamp,kind:'item-consumed',icon:'\\u2212',title:`Used ${qty(g.qty)} \\u00D7 ${g.itemName}`,meta:`${g.title}${g.count>1?` \\u00B7 ${qty(g.count)} use logs combined`:''}${g.market?` \\u00B7 Est. value removed ${money(g.market)}`:''}${g.basis?` \\u00B7 FIFO cost basis removed ${money(g.basis)}`:''}${!g.market&&g.basis?' \\u00B7 Using FIFO cost basis as value fallback':''}`,value:impactKnown?impactValue:0,valueClass:impactKnown?'neg':'',prefix:impactKnown?'-':'',impact:impactKnown?impact:null,impactKnown});}"""
rep(old_consume,new_consume,'consumption impact')

old_cash="""    for(const x of state.cashFlows||[]){const ts=Number(x?.timestamp)||0;if(ts<from||ts>to||x?.transfer||String(x?.direction||'').startsWith('transfer'))continue;const amount=Math.max(0,Number(x?.amount)||0);if(!(amount>0))continue;const incoming=x.direction==='in',isCompany=x.category==='Company Profit / Loss'||x.source==='Company Daily Adjustment';if(isCompany){companySeen=true;companyNet+=incoming?amount:-amount;}const companyMeta=isCompany?`Company daily adjustment \\u00B7 Gross ${money(x.grossIncome)} \\u00B7 Wages ${money(x.wages)} \\u00B7 Advertising ${money(x.advertisementBudget)}`:`${x.category||'Cash'} \\u00B7 ${x.source||'Torn Log'}`;rows.push({timestamp:ts,kind:isCompany?'company-pl':(incoming?'money-in':'money-out'),icon:isCompany?'\\u25A3':(incoming?'\\u2191':'\\u2193'),title:x.title||x.category||(incoming?'Money received':'Money spent'),meta:companyMeta,value:amount,valueClass:incoming?'pos':'neg',prefix:incoming?'+':'-'});}"""
new_cash="""    for(const x of state.cashFlows||[]){const ts=Number(x?.timestamp)||0;if(ts<from||ts>to||x?.transfer||String(x?.direction||'').startsWith('transfer'))continue;const amount=Math.max(0,Number(x?.amount)||0);if(!(amount>0))continue;const incoming=x.direction==='in',impact=incoming?amount:-amount,isCompany=x.category==='Company Profit / Loss'||x.source==='Company Daily Adjustment';if(isCompany){companySeen=true;companyNet+=impact;}const companyMeta=isCompany?`Company daily adjustment \\u00B7 Gross ${money(x.grossIncome)} \\u00B7 Wages ${money(x.wages)} \\u00B7 Advertising ${money(x.advertisementBudget)}`:`${x.category||'Cash'} \\u00B7 ${x.source||'Torn Log'}`;rows.push({timestamp:ts,kind:isCompany?'company-pl':(incoming?'money-in':'money-out'),icon:isCompany?'\\u25A3':(incoming?'\\u2191':'\\u2193'),title:x.title||x.category||(incoming?'Money received':'Money spent'),meta:companyMeta,value:amount,valueClass:incoming?'pos':'neg',prefix:incoming?'+':'-',impact,impactKnown:true});}"""
rep(old_cash,new_cash,'cash impact')

old_return="""    rows.sort((a,b)=>b.timestamp-a.timestamp||String(a.title).localeCompare(String(b.title)));return {from,to,snapshots,before,latest,baseline,delta,rows,companyNet:companySeen?companyNet:null};"""
new_return="""    const valuedRows=rows.filter(x=>x.impactKnown!==false&&Number.isFinite(Number(x.impact))),detectedNet=valuedRows.reduce((n,x)=>n+Number(x.impact),0),unvaluedEvents=rows.length-valuedRows.length;rows.sort((a,b)=>b.timestamp-a.timestamp||String(a.title).localeCompare(String(b.title)));return {from,to,snapshots,before,latest,baseline,delta,rows,companyNet:companySeen?companyNet:null,detectedNet,valuedEvents:valuedRows.length,unvaluedEvents};"""
rep(old_return,new_return,'detected movement return')

old_vars="""    const companyText=d.companyNet==null?'No recorded company P/L':`${d.companyNet>=0?'+':''}${money(d.companyNet)}`;\n    const companyClass=d.companyNet==null?'':d.companyNet>=0?'pos':'neg';\n    const rows=d.rows.slice(0,20).map(x=>`<div class=\"tta-nw-change\"><div class=\"tta-nw-change-icon\">${esc(x.icon)}</div><div class=\"tta-nw-change-copy\"><strong>${esc(x.title)}</strong><small>${esc(tctDateTimeStr(x.timestamp))} TCT \\u00B7 ${esc(x.meta)}</small></div><div class=\"tta-nw-change-value ${x.valueClass||''}\">${x.prefix||''}${money(x.value||0)}</div></div>`).join('');"""
new_vars="""    const companyText=d.companyNet==null?'No recorded company P/L':`${d.companyNet>=0?'+':''}${money(d.companyNet)}`;\n    const companyClass=d.companyNet==null?'':d.companyNet>=0?'pos':'neg';\n    const detectedText=`${d.detectedNet>=0?'+':''}${money(d.detectedNet)}`,detectedClass=d.detectedNet>=0?'pos':'neg',gap=d.delta==null?null:d.delta-d.detectedNet,gapText=gap==null?'Waiting for comparable Torn snapshots':`${gap>=0?'+':''}${money(gap)} difference vs Torn snapshot`;\n    const rows=d.rows.slice(0,20).map(x=>`<div class=\"tta-nw-change\"><div class=\"tta-nw-change-icon\">${esc(x.icon)}</div><div class=\"tta-nw-change-copy\"><strong>${esc(x.title)}</strong><small>${esc(tctDateTimeStr(x.timestamp))} TCT \\u00B7 ${esc(x.meta)}</small></div><div class=\"tta-nw-change-value ${x.valueClass||''}\">${x.impactKnown===false?'\\u2014':`${x.prefix||''}${money(x.value||0)}`}</div></div>`).join('');"""
rep(old_vars,new_vars,'daily net worth display vars')

old_metrics="""<div class=\"tta-nw-daily-metrics\"><div class=\"tta-nw-delta\"><div><small>Torn-reported net-worth movement</small><b class=\"${deltaClass}\">${esc(deltaText)}</b></div><span>${esc(baselineText)}</span></div><div class=\"tta-nw-company-delta\"><small>Recorded company profit / loss</small><b class=\"${companyClass}\">${esc(companyText)}</b><span>${d.companyNet==null?'No company adjustment was recorded for this TCT day.':'Included in analyzer-detected Net Worth activity at the recorded 18:00 TCT company cycle.'}</span></div></div>"""
new_metrics="""<div class=\"tta-nw-daily-metrics\"><div class=\"tta-nw-delta\"><div><small>Analyzer-detected movement</small><b class=\"${detectedClass}\">${esc(detectedText)}</b></div><span>${qty(d.valuedEvents)} valued event${d.valuedEvents===1?'':'s'}${d.unvaluedEvents?` \\u00B7 ${qty(d.unvaluedEvents)} without market value`:''} \\u00B7 ${esc(gapText)}</span></div><div class=\"tta-nw-company-delta\"><small>Torn-reported net-worth movement</small><b class=\"${deltaClass}\">${esc(deltaText)}</b><span>${esc(baselineText)}</span></div><div class=\"tta-nw-company-delta\"><small>Recorded company profit / loss</small><b class=\"${companyClass}\">${esc(companyText)}</b><span>${d.companyNet==null?'No company adjustment was recorded for this TCT day.':'Included in analyzer-detected movement at the recorded 18:00 TCT company cycle.'}</span></div></div>"""
rep(old_metrics,new_metrics,'daily metrics cards')

old_disc="""The Torn total change is calculated only from stored /user/networth snapshots. Company P/L is included in the analyzer-detected activity list and summary, but the analyzer does not rewrite Torn's official net-worth total. The event list may explain movement; it is not a guaranteed one-to-one reconciliation."""
new_disc="""Analyzer-detected movement is the signed sum of valued events shown for this TCT day. Paid item buys include cash paid minus the estimated item value gained; item sales include cash received minus the estimated item value removed. Item values use the analyzer's current Torn catalog price, so historical repricing, unrecognized assets, snapshot timing and Torn's own valuation rules can create a difference from the stored /user/networth snapshot movement. Company P/L is included when recorded."""
rep(old_disc,new_disc,'net worth disclaimer')

p.write_text(s,encoding='ascii')
