from pathlib import Path
import re

p=Path('torn-trade-analyzer.user.js')
s=p.read_text()

s=s.replace('// @version      0.2.1','// @version      0.2.2',1)
s=s.replace("const VERSION = '0.2.1';","const VERSION = '0.2.2';",1)
s=s.replace('Torn cash-flow, spending, earnings, net-worth and trade analytics with fast last-sync updates and optional full-history resync. Data stays on-device.','Torn cash-flow, spending, earnings, net-worth and trade analytics with a clearer Bento dashboard, TCT daily flow and fast sync modes. Data stays on-device.',1)

old="function cashFlowBoundsToday() {const now=Math.min(Number(state.sync?.lastSync)||nowSec(),nowSec());return {from:tctDayStart(now),to:now};}"
new="function cashFlowBoundsToday() {const now=nowSec();return {from:tctDayStart(now),to:now};}"
assert old in s
s=s.replace(old,new,1)

old_nav="""  function financialNavHtml(){return `<div class=\"tta-fin-nav\"><button class=\"tta-btn secondary\" data-act=\"cashflow\"><strong>⇅ Cash Flow</strong><small>income · spending · transfers</small></button><button class=\"tta-btn secondary\" data-act=\"trade\"><strong>▦ Trade Analysis</strong><small>FIFO · acquisitions · profit</small></button><button class=\"tta-btn secondary\" data-act=\"networth\"><strong>◇ Net Worth</strong><small>assets · holdings · portfolio</small></button></div>`;}"""
new_nav="""  function financialNavHtml(){return `<div class=\"tta-fin-nav\" aria-label=\"Financial sections\"><button class=\"tta-navcard\" data-act=\"cashflow\"><span class=\"tta-navsymbol cash\">↕</span><span class=\"tta-navcopy\"><strong>Cash Flow</strong><small>Money in, out & transfers</small></span><span class=\"tta-navarrow\">›</span></button><button class=\"tta-navcard\" data-act=\"trade\"><span class=\"tta-navsymbol trade\">▦</span><span class=\"tta-navcopy\"><strong>Trade Analysis</strong><small>FIFO, acquisitions & profit</small></span><span class=\"tta-navarrow\">›</span></button><button class=\"tta-navcard\" data-act=\"networth\"><span class=\"tta-navsymbol worth\">◇</span><span class=\"tta-navcopy\"><strong>Net Worth</strong><small>Assets, holdings & portfolio</small></span><span class=\"tta-navarrow\">›</span></button></div>`;}\n  function flowLegendHtml(){return `<div class=\"tta-flowlegend\" aria-label=\"Cash flow color guide\"><span><i class=\"in\">+</i> Money in</span><span><i class=\"out\">−</i> Money out</span><span><i class=\"transfer\">↔</i> Transfer</span></div>`;}"""
assert old_nav in s
s=s.replace(old_nav,new_nav,1)

old_break="""  function cashBreakdownHtml(summary,limit=8){const rows=summary.categories.slice(0,limit);return rows.length?`<div class=\"tta-breakdown\">${rows.map(r=>`<div class=\"tta-breakrow\"><span>${esc(r.category)}</span><b class=\"pos\">${r.earned?money(r.earned,true):'—'}</b><b class=\"neg secondary-value\">${r.spent?money(r.spent,true):'—'}</b></div>`).join('')}</div>`:'<div class=\"tta-empty\">No recognized cash movements in this period yet.</div>';}"""
new_break="""  function cashBreakdownHtml(summary,limit=8){const rows=summary.categories.slice(0,limit);return rows.length?`<div class=\"tta-breakdown\"><div class=\"tta-breakhead\"><span>Category</span><b>Money in</b><b>Money out</b></div>${rows.map(r=>`<div class=\"tta-breakrow\"><span>${esc(r.category)}</span><b class=\"pos\">${r.earned?`+${money(r.earned,true)}`:'—'}</b><b class=\"neg secondary-value\">${r.spent?`−${money(r.spent,true)}`:'—'}</b></div>`).join('')}</div>`:'<div class=\"tta-empty\">No recognized cash movements in this period yet.</div>';}"""
assert old_break in s
s=s.replace(old_break,new_break,1)

old_rows="""  function cashFlowRowsHtml(rows,limit=200){return rows.slice(0,limit).map(x=>`<tr><td><span class=\"tta-flowtitle\">${esc(x.title||x.category)}</span><span class=\"tta-flowmeta\">${esc(tctDateTimeStr(x.timestamp))} TCT · ${esc(x.source||x.category)}</span></td><td><span class=\"tta-flowbadge ${x.direction.startsWith('transfer')?'transfer':x.direction}\">${x.direction.startsWith('transfer')?'Transfer':x.direction==='in'?'Incoming':'Outgoing'}</span></td><td>${esc(x.category)}</td><td class=\"num ${x.direction==='in'?'pos':x.direction==='out'?'neg':'tta-transfer'}\">${x.direction==='in'?'+':x.direction==='out'?'-':'↔ '}${money(x.amount)}</td></tr>`).join('')||'<tr><td colspan=\"4\"><div class=\"tta-empty\">No recognized cash flows match this period.</div></td></tr>';}"""
new_rows="""  function cashFlowRowsHtml(rows,limit=200){return rows.slice(0,limit).map(x=>{const isTransfer=x.direction.startsWith('transfer'),symbol=isTransfer?'↔':x.direction==='in'?'+':'−',label=isTransfer?'Transfer':x.direction==='in'?'Money in':'Money out';return `<tr><td><span class=\"tta-flowtitle\">${esc(x.title||x.category)}</span><span class=\"tta-flowmeta\">${esc(tctDateTimeStr(x.timestamp))} TCT · ${esc(x.source||x.category)}</span></td><td><span class=\"tta-flowbadge ${isTransfer?'transfer':x.direction}\"><strong>${symbol}</strong>${label}</span></td><td>${esc(x.category)}</td><td class=\"num ${x.direction==='in'?'pos':x.direction==='out'?'neg':'tta-transfer'}\">${symbol} ${money(x.amount)}</td></tr>`;}).join('')||'<tr><td colspan=\"4\"><div class=\"tta-empty\">No recognized cash flows match this period.</div></td></tr>';}"""
assert old_rows in s
s=s.replace(old_rows,new_rows,1)

new_dashboard=r'''  function dashboardHtml() {
    const today=cashFlowBoundsToday(),sum=cashFlowSummary(today.from,today.to),snap=latestFinancialSnapshot(),portfolio=analyzerPortfolio(),nw=Number(snap?.networth?.total)||0;
    const todayRows=allCashFlows().filter(x=>x.timestamp>=today.from&&x.timestamp<=today.to),recent=todayRows.slice(0,12),lastSync=state.sync?.lastSync?tctDateTimeStr(state.sync.lastSync):'';
    return `${header('Cash Flow Analyzer',`v${VERSION} · simple financial overview`)}<div class="tta-content tta-dashboard">
      ${!hasApiKey()?'<div class="tta-banner"><strong>Preview mode.</strong> Add a Torn API key in Settings to build your financial ledger.</div>':''}
      <div class="tta-period tta-dashboard-top"><div><small>Today · Torn City Time</small><strong>${esc(tctDateStr(today.from))}</strong><span class="tta-periodhint">${lastSync?`Last sync ${esc(lastSync)} TCT`:'Run Quick Sync to load today’s movements'}</span></div><div class="tta-syncactions"><button class="tta-btn" data-act="syncQuick" ${state.syncing?'disabled':''}>${state.syncing?'Syncing…':'⚡ Quick Sync'}</button><button class="tta-btn secondary" data-act="syncFull" ${state.syncing?'disabled':''}>⟳ Full Resync</button></div></div>
      <div class="tta-bento-grid tta-cash-bento">
        <section class="tta-bento tta-bento-hero"><div class="tta-bento-kicker">Consolidated cash flow today</div><b class="tta-consolidated ${sum.net>=0?'pos':'neg'}">${money(sum.net)}</b><div class="tta-flow-equation"><span class="in">+ ${money(sum.earned)}</span><span>−</span><span class="out">${money(sum.spent)}</span></div><small>Money in minus money out for the current TCT day. Internal transfers do not change this total.</small></section>
        <section class="tta-bento tta-bento-mini in"><span class="tta-mini-symbol">+</span><div><small>Money in today</small><b>${money(sum.earned)}</b></div></section>
        <section class="tta-bento tta-bento-mini out"><span class="tta-mini-symbol">−</span><div><small>Money out today</small><b>${money(sum.spent)}</b></div></section>
        <section class="tta-bento tta-bento-transfer"><span class="tta-mini-symbol">↔</span><div><small>Internal transfers today</small><b>${money(sum.transferIn+sum.transferOut)}</b><em>Tracked separately so moving your own money is not treated as income or spending.</em></div></section>
      </div>
      ${flowLegendHtml()}
      <div class="tta-sectionintro"><div><small>Explore</small><h3>Financial tools</h3></div><span>Swipe cards sideways</span></div>
      ${financialNavHtml()}
      <div class="tta-sectionintro"><div><small>Snapshot</small><h3>Financial position</h3></div></div>
      <div class="tta-bento-grid tta-position-bento"><section class="tta-bento"><small>Torn net worth</small><b>${snap?.networth?money(nw):'Sync to load'}</b></section><section class="tta-bento"><small>Recorded inventory value</small><b>${money(portfolio.marketValue)}</b></section><section class="tta-bento"><small>Realized trade profit</small><b class="${portfolio.realizedProfit>=0?'pos':'neg'}">${money(portfolio.realizedProfit)}</b></section></div>
      <section class="tta-glass-section"><div class="tta-sectionhead"><div><small>Current TCT day</small><h3>Today’s cash movements</h3><span class="tta-sectionhint">${qty(todayRows.length)} recorded movement${todayRows.length===1?'':'s'} today</span></div><button class="tta-btn secondary" data-act="cashflow">Open ledger</button></div><div class="tta-table-scroll"><table class="tta-flowtable"><tbody>${cashFlowRowsHtml(recent,12)}</tbody></table></div>${todayRows.length>12?`<div class="tta-morehint">Showing the latest 12 of ${qty(todayRows.length)} movements from today.</div>`:''}</section>
    </div>`;
  }
'''
pat=r"  function dashboardHtml\(\) \{.*?\n  \}\n  function cashFlowDateRange"
s2,n=re.subn(pat,new_dashboard+"  function cashFlowDateRange",s,count=1,flags=re.S)
assert n==1,n
s=s2

new_cashflow=r'''  function cashFlowHtml() {
    const {from,to}=cashFlowDateRange(),sum=cashFlowSummary(from,to),q=String(state.cashSearch||'').trim().toLowerCase(),cat=String(state.cashCategory||'all');let rows=allCashFlows().filter(x=>x.timestamp>=from&&x.timestamp<=to);if(cat!=='all')rows=rows.filter(x=>x.category===cat);if(q)rows=rows.filter(x=>`${x.title} ${x.category} ${x.source}`.toLowerCase().includes(q));const cats=[...new Set(allCashFlows().map(x=>x.category))].sort();
    return `${header('Cash Flow','Understand where your money comes from and where it goes',true)}<div class="tta-content">${periodChipsHtml()}<div class="tta-bento-grid tta-cash-bento tta-page-bento"><section class="tta-bento tta-bento-hero"><div class="tta-bento-kicker">Consolidated cash flow</div><b class="tta-consolidated ${sum.net>=0?'pos':'neg'}">${money(sum.net)}</b><div class="tta-flow-equation"><span class="in">+ ${money(sum.earned)}</span><span>−</span><span class="out">${money(sum.spent)}</span></div><small>Money in minus money out for the selected period. Transfers are shown separately.</small></section><section class="tta-bento tta-bento-mini in"><span class="tta-mini-symbol">+</span><div><small>Money in</small><b>${money(sum.earned)}</b></div></section><section class="tta-bento tta-bento-mini out"><span class="tta-mini-symbol">−</span><div><small>Money out</small><b>${money(sum.spent)}</b></div></section></div>${flowLegendHtml()}<section class="tta-glass-section"><div class="tta-sectionintro"><div><small>Summary</small><h3>By category</h3></div></div>${cashBreakdownHtml(sum,20)}</section><div class="tta-listtools"><input id="tta-cash-search" class="tta-history-search" placeholder="Search cash flow…" value="${esc(state.cashSearch||'')}"><select id="tta-cash-category" class="tta-history-search"><option value="all">All categories</option>${cats.map(c=>`<option value="${esc(c)}" ${cat===c?'selected':''}>${esc(c)}</option>`).join('')}</select></div><section class="tta-glass-section"><div class="tta-sectionintro"><div><small>Ledger</small><h3>Money movements</h3></div><span>${qty(rows.length)} result${rows.length===1?'':'s'}</span></div><div class="tta-ledgerwrap"><table class="tta-flowtable"><thead><tr><th>Event</th><th>Flow</th><th>Category</th><th style="text-align:right">Amount</th></tr></thead><tbody>${cashFlowRowsHtml(rows)}</tbody></table></div></section><div class="tta-note tta-friendly-note">Transfers stay visible but are excluded from money-in and money-out totals. Item sales and purchases use the analyzer’s normalized trade history.</div></div>`;
  }
'''
pat2=r"  function cashFlowHtml\(\) \{.*?\n  \}\n  function labeledKey"
s2,n=re.subn(pat2,new_cashflow+"  function labeledKey",s,count=1,flags=re.S)
assert n==1,n
s=s2

css=r'''
      /* v0.2.2 Bento / glass visual system */
      :root{--tta-bg:#182630;--tta-panel:#20313d;--tta-card:#263946;--tta-soft:#304653;--tta-line:#ffffff20;--tta-text:#f5f9fc;--tta-muted:#c7d4de;--tta-faint:#a8bac8;--tta-green:#77ddb0;--tta-red:#ff979d;--tta-blue:#8bc9f7;--tta-yellow:#f1c875;--tta-glass:#ffffff0d;--tta-glass-strong:#ffffff14;--tta-shadow:0 12px 32px #07131c3d}
      #tta-root{background:#0d1820b8;backdrop-filter:blur(8px);-webkit-backdrop-filter:blur(8px)}
      .tta-shell{overflow-y:auto!important;overflow-x:hidden!important;background:radial-gradient(circle at 12% 0%,#31536555 0,transparent 34%),radial-gradient(circle at 92% 18%,#28554842 0,transparent 30%),linear-gradient(180deg,#1a2a35 0%,#15232d 100%);scrollbar-gutter:stable}
      .tta-content{width:min(100%,760px)!important;max-width:760px!important;min-width:0!important;overflow-x:hidden;padding:14px 12px 34px}
      .tta-content>*{min-width:0;max-width:100%}
      .tta-header{background:#1c2b35d9;border-bottom:1px solid #ffffff1d;backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px);box-shadow:0 8px 24px #07131c24}
      .tta-mark{background:linear-gradient(145deg,#326052,#31566d);box-shadow:inset 0 1px #ffffff24,0 8px 20px #07131c33}
      .tta-title{font-size:16px}.tta-sub{color:#cbd8e2}
      .tta-iconbtn,.tta-back,.tta-btn.secondary,.tta-chip,.tta-history-search{background:#ffffff0d;border-color:#ffffff20;box-shadow:inset 0 1px #ffffff0d}
      .tta-btn{border-radius:12px;background:linear-gradient(135deg,#7be0b4,#89c9f7);color:#10232b!important;box-shadow:0 7px 18px #0d1b2430;font-weight:850}.tta-btn.secondary{color:var(--tta-text)!important}.tta-btn.danger{background:#66353c80;border-color:#ff9aa944;color:#ffd9dc!important}
      .tta-chip{color:#d8e3ea!important}.tta-chip.active{background:linear-gradient(135deg,#7be0b4,#91d7c2);border-color:transparent;color:#123027!important}
      .tta-period{background:#ffffff08;border:1px solid #ffffff15;border-radius:16px;padding:11px 12px;box-shadow:inset 0 1px #ffffff0b}.tta-periodhint{display:block;margin-top:3px;color:var(--tta-faint);font-size:9px}
      .tta-dashboard-top{align-items:flex-start}.tta-syncactions{max-width:100%;flex:0 0 auto}.tta-syncactions .tta-btn{min-height:34px;padding:7px 9px;font-size:10px}
      .tta-bento-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin:10px 0}.tta-bento{min-width:0;border:1px solid #ffffff1f;border-radius:18px;background:linear-gradient(145deg,#ffffff12,#ffffff08);box-shadow:var(--tta-shadow),inset 0 1px #ffffff16;backdrop-filter:blur(14px);-webkit-backdrop-filter:blur(14px);padding:13px;color:var(--tta-text)}
      .tta-bento>small,.tta-bento-kicker{display:block;color:var(--tta-muted);font-size:9px;font-weight:750;text-transform:uppercase;letter-spacing:.55px}.tta-bento>b{display:block;margin-top:5px;font-size:16px;font-variant-numeric:tabular-nums;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
      .tta-bento-hero{grid-column:1/-1;padding:17px;background:linear-gradient(135deg,#ffffff18,#70bfa40d 58%,#6eb7e817);position:relative;overflow:hidden}.tta-bento-hero:after{content:"";position:absolute;width:150px;height:150px;border-radius:50%;right:-60px;top:-70px;background:#8bc9f718;filter:blur(2px);pointer-events:none}.tta-consolidated{display:block;position:relative;z-index:1;font-size:31px!important;line-height:1.08;margin:7px 0 8px!important;letter-spacing:-.7px}.tta-flow-equation{display:flex;align-items:center;gap:7px;flex-wrap:wrap;color:var(--tta-muted);font-size:10px;font-weight:750}.tta-flow-equation .in{color:var(--tta-green)}.tta-flow-equation .out{color:var(--tta-red)}.tta-bento-hero>small:last-child{display:block;position:relative;z-index:1;margin-top:8px;color:var(--tta-faint);font-size:9px;line-height:1.45;text-transform:none;letter-spacing:0;font-weight:500}
      .tta-bento-mini{display:flex;align-items:center;gap:10px}.tta-bento-mini .tta-mini-symbol,.tta-bento-transfer .tta-mini-symbol{width:31px;height:31px;flex:0 0 31px;display:grid;place-items:center;border-radius:11px;font-size:18px;font-weight:900}.tta-bento-mini.in .tta-mini-symbol{background:#77ddb01f;color:var(--tta-green)}.tta-bento-mini.out .tta-mini-symbol{background:#ff979d1f;color:var(--tta-red)}.tta-bento-mini small,.tta-bento-transfer small{display:block;color:var(--tta-muted);font-size:9px}.tta-bento-mini b,.tta-bento-transfer b{display:block;margin-top:2px;font-size:14px}.tta-bento-mini.in b{color:var(--tta-green)}.tta-bento-mini.out b{color:var(--tta-red)}
      .tta-bento-transfer{grid-column:1/-1;display:flex;align-items:center;gap:10px;padding:10px 13px}.tta-bento-transfer .tta-mini-symbol{background:#8bc9f71f;color:var(--tta-blue)}.tta-bento-transfer em{display:block;margin-top:2px;color:var(--tta-faint);font-size:8.5px;font-style:normal;line-height:1.35}
      .tta-flowlegend{display:flex;gap:7px;align-items:center;overflow-x:auto;max-width:100%;padding:2px 1px 8px;scrollbar-width:none}.tta-flowlegend::-webkit-scrollbar{display:none}.tta-flowlegend span{flex:0 0 auto;display:inline-flex;align-items:center;gap:5px;color:var(--tta-muted);font-size:9px}.tta-flowlegend i{width:20px;height:20px;display:grid;place-items:center;border-radius:7px;font-style:normal;font-weight:900}.tta-flowlegend i.in{background:#77ddb01c;color:var(--tta-green)}.tta-flowlegend i.out{background:#ff979d1c;color:var(--tta-red)}.tta-flowlegend i.transfer{background:#8bc9f71c;color:var(--tta-blue)}
      .tta-sectionintro{display:flex;align-items:flex-end;justify-content:space-between;gap:10px;margin:15px 2px 8px}.tta-sectionintro small,.tta-sectionhead small{display:block;color:var(--tta-faint);font-size:8px;text-transform:uppercase;letter-spacing:.6px}.tta-sectionintro h3,.tta-sectionhead h3{margin:1px 0 0;color:var(--tta-text);font-size:14px}.tta-sectionintro>span,.tta-sectionhint,.tta-morehint{color:var(--tta-faint);font-size:8.5px}
      .tta-fin-nav{display:flex!important;grid-template-columns:none!important;gap:9px;margin:0 0 13px;padding:1px 2px 8px;overflow-x:auto!important;overflow-y:hidden!important;max-width:100%;width:100%;scroll-snap-type:x proximity;overscroll-behavior-x:contain;-webkit-overflow-scrolling:touch;scrollbar-width:none}.tta-fin-nav::-webkit-scrollbar{display:none}.tta-navcard{flex:0 0 clamp(174px,58vw,220px);scroll-snap-align:start;display:grid;grid-template-columns:36px minmax(0,1fr) 18px;align-items:center;gap:9px;min-height:70px;padding:11px;border:1px solid #ffffff1e;border-radius:17px;background:linear-gradient(145deg,#ffffff13,#ffffff08);color:var(--tta-text)!important;box-shadow:var(--tta-shadow),inset 0 1px #ffffff14;text-align:left}.tta-navsymbol{width:36px;height:36px;display:grid;place-items:center;border-radius:12px;font-size:18px;font-weight:900}.tta-navsymbol.cash{background:#77ddb01d;color:var(--tta-green)}.tta-navsymbol.trade{background:#8bc9f71d;color:var(--tta-blue)}.tta-navsymbol.worth{background:#f1c8751c;color:var(--tta-yellow)}.tta-navcopy{min-width:0}.tta-navcopy strong{display:block;color:var(--tta-text);font-size:11px}.tta-navcopy small{display:block;margin-top:3px;color:var(--tta-faint);font-size:8.5px;line-height:1.3;white-space:normal}.tta-navarrow{color:var(--tta-faint);font-size:22px;text-align:right}
      .tta-position-bento{grid-template-columns:repeat(3,minmax(0,1fr))}.tta-position-bento .tta-bento{padding:11px}.tta-position-bento .tta-bento b{font-size:13px}
      .tta-glass-section,.tta-fin-section,.tta-chartcard,.tta-item,.tta-keycard,.tta-tos,.tta-banner,.tta-ledgerwrap{background:linear-gradient(145deg,#ffffff10,#ffffff07)!important;border:1px solid #ffffff1b!important;box-shadow:var(--tta-shadow),inset 0 1px #ffffff10;border-radius:18px!important;backdrop-filter:blur(12px);-webkit-backdrop-filter:blur(12px)}
      .tta-glass-section{padding:12px;margin:11px 0}.tta-fin-section{padding:12px}.tta-chartcard{padding:13px 11px}.tta-item{margin-bottom:10px}.tta-accordion,.tta-metric{background:#ffffff07!important}.tta-ministat,.tta-stat,.tta-cashcard{background:#ffffff0b!important;border-color:#ffffff18!important;box-shadow:inset 0 1px #ffffff0d}.tta-summary{gap:9px}.tta-stat{border-radius:15px}.tta-stat label,.tta-metric small,.tta-ministat small,.tta-cashcard small{color:var(--tta-muted)!important}.tta-stat b,.tta-metric b,.tta-ministat b,.tta-cashcard b{color:var(--tta-text)}
      .tta-cashhero{gap:9px}.tta-cashcard{border-radius:16px;padding:12px}.tta-cashcard b{font-size:15px}.tta-fin-row{border-bottom-color:#ffffff14}.tta-note{color:#bfd0dc;background:#ffffff07;border:1px solid #ffffff12;border-radius:12px;padding:9px 10px}.tta-friendly-note{margin-top:10px}.tta-source,.tta-snapshot-note,.tta-listmeta{color:#b4c5d1!important}
      .tta-breakdown{gap:6px}.tta-breakhead,.tta-breakrow{display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:8px;align-items:center}.tta-breakhead{padding:0 8px 3px;color:var(--tta-faint);font-size:8px;text-transform:uppercase;letter-spacing:.45px}.tta-breakhead b{text-align:right}.tta-breakrow{background:#ffffff08;border-color:#ffffff16;border-radius:11px;padding:8px}.tta-breakrow span{color:#e9f1f6}.tta-breakrow b{font-size:9px}
      .tta-flowtable{min-width:560px}.tta-table-scroll,.tta-ledgerwrap{width:100%;max-width:100%;overflow-x:auto!important;overflow-y:hidden;overscroll-behavior-x:contain;-webkit-overflow-scrolling:touch}.tta-ledgerwrap{border-radius:14px!important}.tta-flowtable th{color:#afc1ce;border-bottom-color:#ffffff19}.tta-flowtable td{border-bottom-color:#ffffff12;color:#e8f0f5}.tta-flowmeta{color:#9fb2c0}.tta-flowbadge{display:inline-flex;align-items:center;gap:4px;border-radius:8px;padding:4px 7px}.tta-flowbadge strong{font-size:11px}.tta-flowbadge.in{background:#77ddb019;border-color:#77ddb033}.tta-flowbadge.out{background:#ff979d19;border-color:#ff979d33}.tta-flowbadge.transfer{background:#8bc9f719;border-color:#8bc9f733}
      .tta-history-search{color:#f5f9fc!important}.tta-history-search::placeholder{color:#9eb0bd}.tta-history-search:focus{background:#ffffff12}.tta-seg{background:#ffffff08;border-color:#ffffff18}.tta-seg button.active{background:#ffffff14}.tta-chartviewport{max-width:100%}.tta-axis{fill:#dce7ee!important;color:#dce7ee!important;stroke:#1a2a35}.tta-grid{stroke:#ffffff18}.tta-zero{stroke:#a8bac8}.tta-charttooltip{background:#20313df2;border-color:#ffffff24;box-shadow:0 12px 30px #07131c66}
      .tta-itemfacts{gap:5px}.tta-factpill{background:#ffffff08;border-color:#ffffff16;color:#b8c8d4}.tta-factpill.market{background:#77ddb015;border-color:#77ddb02c;color:var(--tta-green)}.tta-thumbwrap{background:#ffffff08;border-color:#ffffff18}.tta-profitbox{min-width:70px}.tta-metrics{background:#ffffff18;border-top-color:#ffffff18}.tta-chevron{color:#aebfcb}
      .tta-empty{min-height:110px;color:#bdccd6}.tta-banner{color:#dbe6ed}.tta-status-banner{background:#8bc9f70f!important}.tta-toast{background:#20313df5!important;border-color:#ffffff22!important;color:#f5f9fc!important}
      @media(max-width:520px){.tta-content{padding-left:10px;padding-right:10px}.tta-period{align-items:stretch;flex-direction:column}.tta-syncactions{width:100%;display:grid;grid-template-columns:1fr 1fr}.tta-syncactions .tta-btn{width:100%}.tta-position-bento{grid-template-columns:repeat(2,minmax(0,1fr))}.tta-position-bento .tta-bento:last-child{grid-column:1/-1}.tta-navcard{flex-basis:72vw}.tta-listtools{grid-template-columns:1fr}.tta-consolidated{font-size:28px!important}}
      @media(min-width:700px){.tta-bento-grid.tta-cash-bento{grid-template-columns:1.35fr .8fr .8fr}.tta-bento-grid.tta-cash-bento .tta-bento-hero{grid-column:auto;grid-row:span 2}.tta-bento-grid.tta-cash-bento .tta-bento-transfer{grid-column:2/-1}.tta-navcard{flex-basis:220px}}
'''
anchor='      @media(prefers-reduced-motion:reduce){.tta-loadingbar span,.tta-spinner,.tta-fabspinner{animation-duration:2.2s}.tta-item,.tta-btn,.tta-chip,.tta-iconbtn,.tta-back,.tta-pin,.tta-toast{transition:none}}\n'
assert anchor in s
s=s.replace(anchor,anchor+css,1)

r=Path('README.md')
rd=r.read_text()
rd=rd.replace('**Current version:** v0.2.1','**Current version:** v0.2.2',1)
rd += '''\n\n## v0.2.2 — Bento UI refresh\n\n- Dashboard redesigned into a lighter Bento-style glass layout with clearer visual hierarchy and more readable text.\n- Financial navigation cards now scroll horizontally inside their own strip; the analyzer page itself is constrained from horizontal scrolling.\n- Today is always based on the current Torn City Time day, not the previous sync date.\n- Added a top-level consolidated cash-flow figure: money in minus money out for the current TCT day. Internal transfers remain separate.\n- Added consistent flow legend and clearer + / − / ↔ symbols for money in, money out and transfers.\n- Recent cash movements on the dashboard are explicitly limited to the current TCT day.\n'''
r.write_text(rd)
