from pathlib import Path

p=Path('torn-trade-analyzer.user.js')
s=p.read_text()

s=s.replace('// @version      0.2.3','// @version      0.2.4',1)
s=s.replace("const VERSION = '0.2.3';","const VERSION = '0.2.4';",1)
s=s.replace('Torn cash-flow, spending, earnings, net-worth and trade analytics with a Bento dashboard, reliable floating launcher, TCT daily flow and fast sync modes. Data stays on-device.','Torn cash-flow, spending, earnings, net-worth and trade analytics with a Bento dashboard, isolated floating launcher, TCT daily flow and fast sync modes. Data stays on-device.',1)

old_svg='''  function fabIconSvg() {\n    return `<span class="tta-fabicon" aria-hidden="true"><svg viewBox="0 0 24 24" focusable="false"><defs><linearGradient id="ttaFabPulse" x1="5" y1="0" x2="20" y2="0" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#63efb1"/><stop offset="1" stop-color="#7fc1ff"/></linearGradient></defs><rect class="tta-terminal-frame" x="2.5" y="3.25" width="19" height="17.5" rx="3"/><path class="tta-terminal-bar" d="M3.25 7h17.5"/><circle cx="5.25" cy="5.2" r=".65" fill="#63efb1"/><circle cx="7.45" cy="5.2" r=".65" fill="#7fc1ff"/><path class="tta-terminal-prompt" d="M5.4 10.1l2 1.8-2 1.8"/><path class="tta-terminal-cursor" d="M8.8 13.7h2.2"/><path class="tta-data-pulse" d="M5 17.25h2.15l1.05-2.05 1.45 3.5 1.75-5.15 1.55 3.7h1.85l1.1-1.8 1.05 1.8H19"/></svg></span>`;\n  }'''
new_svg='''  function fabIconSvg() {\n    return `<span class="tta-fabicon" aria-hidden="true" style="display:grid;place-items:center;width:23px;height:23px;pointer-events:none"><svg viewBox="0 0 24 24" focusable="false" style="display:block;width:23px;height:23px;overflow:visible;filter:drop-shadow(0 0 4px #63efb144)"><defs><linearGradient id="ttaFabPulse" x1="5" y1="0" x2="20" y2="0" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#63efb1"/><stop offset="1" stop-color="#7fc1ff"/></linearGradient></defs><rect x="2.5" y="3.25" width="19" height="17.5" rx="3" fill="#0a1219" stroke="#7fc1ff" stroke-width="1.35"/><path d="M3.25 7h17.5" fill="none" stroke="#38566a" stroke-width="1.15"/><circle cx="5.25" cy="5.2" r=".65" fill="#63efb1"/><circle cx="7.45" cy="5.2" r=".65" fill="#7fc1ff"/><path d="M5.4 10.1l2 1.8-2 1.8" fill="none" stroke="#63efb1" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round"/><path d="M8.8 13.7h2.2" fill="none" stroke="#b9c8d6" stroke-width="1.35" stroke-linecap="round"/><path d="M5 17.25h2.15l1.05-2.05 1.45 3.5 1.75-5.15 1.55 3.7h1.85l1.1-1.8 1.05 1.8H19" fill="none" stroke="url(#ttaFabPulse)" stroke-width="1.55" stroke-linecap="round" stroke-linejoin="round"/></svg></span>`;\n  }'''
assert old_svg in s
s=s.replace(old_svg,new_svg,1)

old_update='''  function updateFabState() {\n    const fab=document.getElementById('tta-fab');if(!fab)return;\n    const syncing=!!state.syncing;\n    fab.classList.toggle('syncing',syncing);\n    fab.setAttribute('aria-label',syncing?'Cash Flow Analyzer syncing':'Cash Flow Analyzer');\n    fab.title=syncing?'Financial history sync is running · tap to reopen':'Open Cash Flow Analyzer';\n    fab.innerHTML=syncing?'<span class="tta-fabspinner" aria-hidden="true"></span>':fabIconSvg();\n    fab.classList.toggle('tta-fab-hidden',!!state.open);fab.style.removeProperty('display');\n    requestAnimationFrame(()=>applyFabPosition(fab));\n  }\n  function ensureFabMounted() {\n    let fab=document.getElementById('tta-fab');\n    if(!fab){fab=document.createElement('button');fab.id='tta-fab';fab.innerHTML=fabIconSvg();(document.body||document.documentElement).appendChild(fab);bindFabDrag(fab);}\n    else if(!fab.isConnected)(document.body||document.documentElement).appendChild(fab);\n    bindFabDrag(fab);updateFabState();requestAnimationFrame(()=>applyFabPosition(fab));return fab;\n  }'''
new_update='''  function forceFabBaseStyle(fab) {\n    if(!fab)return;const st=fab.style,set=(k,v)=>st.setProperty(k,v,'important');\n    set('position','fixed');set('z-index','2147483647');set('width','40px');set('height','40px');set('min-width','40px');set('min-height','40px');set('max-width','40px');set('max-height','40px');set('padding','0');set('margin','0');set('border','1px solid #4f768b');set('border-radius','50%');set('background','linear-gradient(135deg,#244c42,#254d68)');set('color','#fff');set('box-shadow','0 10px 26px #0008,0 0 0 1px #ffffff12 inset');set('visibility','visible');set('opacity','1');set('pointer-events','auto');set('align-items','center');set('justify-content','center');set('text-align','center');set('overflow','visible');set('transform','none');set('filter','none');set('clip','auto');set('clip-path','none');set('contain','none');set('isolation','isolate');set('touch-action','none');\n  }\n  function resetFabToDefault(fab) {\n    state.fabPosition=null;save('fabPosition',null);fab.style.removeProperty('left');fab.style.removeProperty('top');fab.style.setProperty('right','14px','important');fab.style.setProperty('bottom','96px','important');\n  }\n  function verifyFabViewport(fab) {\n    if(!fab||state.open)return;const r=fab.getBoundingClientRect(),bad=!Number.isFinite(r.left)||!Number.isFinite(r.top)||r.width<20||r.height<20||r.right<4||r.bottom<4||r.left>window.innerWidth-4||r.top>window.innerHeight-4;\n    if(bad){resetFabToDefault(fab);requestAnimationFrame(()=>applyFabPosition(fab));}\n  }\n  function updateFabState() {\n    const fab=document.getElementById('tta-fab');if(!fab)return;\n    forceFabBaseStyle(fab);const syncing=!!state.syncing;\n    fab.classList.toggle('syncing',syncing);\n    fab.setAttribute('aria-label',syncing?'Cash Flow Analyzer syncing':'Cash Flow Analyzer');\n    fab.title=syncing?'Financial history sync is running · tap to reopen':'Open Cash Flow Analyzer';\n    fab.innerHTML=syncing?'<span class="tta-fabspinner" aria-hidden="true"></span>':fabIconSvg();\n    fab.classList.toggle('tta-fab-hidden',!!state.open);fab.style.setProperty('display',state.open?'none':'inline-flex','important');\n    requestAnimationFrame(()=>{applyFabPosition(fab);forceFabBaseStyle(fab);verifyFabViewport(fab);});\n  }\n  function ensureFabMounted() {\n    let fab=document.getElementById('tta-fab');const host=document.documentElement;\n    if(!fab){fab=document.createElement('button');fab.id='tta-fab';fab.type='button';fab.innerHTML=fabIconSvg();host.appendChild(fab);bindFabDrag(fab);}\n    else if(fab.parentElement!==host){host.appendChild(fab);}\n    forceFabBaseStyle(fab);bindFabDrag(fab);updateFabState();requestAnimationFrame(()=>{applyFabPosition(fab);verifyFabViewport(fab);});return fab;\n  }'''
assert old_update in s
s=s.replace(old_update,new_update,1)

old_mount="""    if(!window.__ttaFabWatch){window.__ttaFabWatch=true;const host=document.documentElement;new MutationObserver(()=>{if(!document.getElementById('tta-fab'))ensureFabMounted();}).observe(host,{childList:true,subtree:true});setInterval(()=>{if(!document.getElementById('tta-fab'))ensureFabMounted();else updateFabState();},3000);}"""
new_mount="""    if(!window.__ttaFabWatch){window.__ttaFabWatch=true;const host=document.documentElement;new MutationObserver(()=>{const fab=document.getElementById('tta-fab');if(!fab||fab.parentElement!==host)ensureFabMounted();}).observe(host,{childList:true,subtree:true});setInterval(()=>{const fab=document.getElementById('tta-fab');if(!fab||fab.parentElement!==host)ensureFabMounted();else{updateFabState();verifyFabViewport(fab);}},1500);}"""
assert old_mount in s
s=s.replace(old_mount,new_mount,1)

p.write_text(s)

r=Path('README.md')
read=r.read_text()
read=read.replace('**Current version:** v0.2.3','**Current version:** v0.2.4',1)
read += '''\n\n## v0.2.4 — isolated Torn PDA launcher\n\n- Mounts the floating launcher directly under the document root rather than inside Torn's body layout.\n- Forces critical launcher visibility, size, position and stacking styles inline with `!important`.\n- Resets an invalid/off-screen saved launcher position back to a safe default.\n- Embeds the terminal/data-pulse SVG styling directly in the icon so Torn CSS cannot make the icon disappear.\n- Rechecks launcher presence and viewport visibility during Torn SPA navigation.\n'''
r.write_text(read)
