const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.resolve(__dirname, '..');
const read = name => fs.readFileSync(path.join(root, 'src', name), 'utf8');
const files = ['state.js', 'diagnostics.js', 'persistence.js', 'launcher.js', 'fifo.js', 'accounting.js', 'views.js', 'settings.js', 'controller.js', 'parsers.js', 'fixtures.js', 'sync.js', 'bootstrap.js'];
const css = read('styles.css');
const style = `  function injectCss() {\n    if (document.getElementById('tta-css')) return;\n    const style = document.createElement('style');\n    style.id = 'tta-css';\n    style.textContent = ${JSON.stringify(css)};\n    document.head.appendChild(style);\n  }\n`;
const output = read('metadata.txt') + "// Generated by tools/build.cjs. Edit src/ instead.\n(() => {\n  'use strict';\n\n" + files.map(name => `\n  // Source: ${name}\n${read(name)}`).join('\n') + style + '\n})();\n';
new vm.Script(output, { filename: 'torn-trade-analyzer.user.js' });
new vm.Script(output.replaceAll('_###PDA-APIKEY###_', 'testpda0123456789'), { filename: 'pda-substituted.user.js' });
const target = path.join(root, 'torn-trade-analyzer.user.js');
if (process.argv.includes('--check')) {
  if (fs.readFileSync(target, 'utf8').replace(/\r\n/g, '\n') !== output) throw new Error('Generated userscript is out of date. Run npm run build.');
} else fs.writeFileSync(target, output);
console.log('Userscript and Torn PDA syntax verified.');
